const permissionFlags = {
  AddReactions: "반응 추가하기",
  Administrator: "관리자",
  AttachFiles: "파일 첨부",
  BanMembers: "멤버 차단하기",
  BypassSlowmode: "슬로우 모드 우회",
  ChangeNickname: "별명 변경하기",
  Connect: "연결",
  CreateEvents: "이벤트 생성하기",
  CreateGuildExpressions: "표현 만들기",
  CreateInstantInvite: "초대 코드 만들기",
  CreatePrivateThreads: "비공개 스레드 만들기",
  CreatePublicThreads: "공개 스레드 만들기",
  DeafenMembers: "멤버의 헤드셋 음소거하기",
  EmbedLinks: "링크 첨부",
  KickMembers: "멤버 추방, 승인, 거부",
  ManageChannels: "채널 관리하기",
  ManageEmojisAndStickers: "이모지 및 스티커 관리하기",
  ManageEvents: "이벤트 관리",
  ManageGuild: "서버 관리하기",
  ManageGuildExpressions: "표현 관리하기",
  ManageMessages: "메시지 관리",
  ManageNicknames: "별명 관리하기",
  ManageRoles: "역할 관리하기",
  ManageThreads: "스레드 및 포스트 관리하기",
  ManageWebhooks: "웹후크 관리하기",
  MentionEveryone: "@everyone, @here, 모든 역할 멘션하기",
  ModerateMembers: "타임아웃 멤버",
  MoveMembers: "멤버 이동",
  MuteMembers: "멤버들의 마이크 음소거하기",
  PinMessages: "메시지 고정",
  PrioritySpeaker: "우선 발언권",
  ReadMessageHistory: "메시지 기록 보기",
  RequestToSpeak: "발언권 요청하기",
  SendMessages: "메시지 보내기 및 포스트 만들기",
  SendMessagesInThreads: "스레드와 포스트에서 메시지 보내기",
  SendPolls: "투표 만기",
  SendTTSMessages: "텍스트 음성 변환 메시지 전송",
  SendVoiceMessages: "음성 메시지 보내기",
  Speak: "말하기",
  Stream: "영상",
  UseApplicationCommands: "애플리케이션 명령어 사용",
  UseEmbeddedActivities: "활동 사용하기",
  UseExternalApps: "외부 앱 사용",
  UseExternalEmojis: "외부 이모지 사용",
  UseExternalSounds: "외부 사운드 사용",
  UseExternalStickers: "외부 스티커 사용",
  UseSoundboard: "사운드보드 사용",
  UseVAD: "음성 감지 사용",
  ViewAuditLog: "감사 로그 보기",
  ViewChannel: "채널 보기",
  ViewCreatorMonetizationAnalytics: "크리에이터 수익 분석 보기",
  ViewGuildInsights: "서버 인사이트 보기",
};

export { permissionFlags };
